WIN_WIDTH = 1000
WIN_HEIGHT = 500
BTN_WIDTH = 300
BTN_HEIGHT = 40
PADDING = 5
PADDING_LEFT = 10
PROTOCOLS_ACCEPTED_DIR = "\\ProtocolsAccepted"
PROTOCOLS_APPEAL_DIR = "\\ProtocolsAppeal"
TEST_FILES_DIR = "\\TestFiles"
STATUS_ACCEPTED = "Zaakceptowany"
STATUS_TO_ACCEPT = "Do zaakceptowania"
STATUS_IN_APPEAL = "W trakcie odwołania"
